// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Solo corre con `npx prisma db seed` explícito — no se engancha a
    // `migrate deploy` (ver prisma/seed.ts, Fase G). Usa un tsconfig propio
    // (prisma/tsconfig.seed.json) que fuerza CommonJS: con "module":
    // "nodenext" (tsconfig.json base), el detector de formato ESM/CJS de
    // ts-node rompe con "Unknown file extension .ts" al ejecutar un script
    // suelto.
    seed: "npx ts-node --project prisma/tsconfig.seed.json prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Solo lo usan `prisma migrate dev` y `prisma migrate diff
    // --from-migrations` (ej. el chequeo de drift en CI) — `migrate
    // deploy`, el comando que corre en producción, no lo necesita.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
